name: Daily Download of Schedule File

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Optional for manual triggering

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download schedule file
        run: |
          curl -o schedule.js "https://daddylive.mp/schedule/schedule-generated.php"

      - name: Configure Git for push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Commit changes if file updated
        run: |
          if [ -n "$(git status --porcelain schedule.js)" ]; then
            git add schedule.js
            git commit -m "Update schedule file [skip ci]"
            git push
          else
            echo "No changes in schedule.js"
          fi
