name: Update Schedule
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download schedule
        run: |
          # Add browser-like headers and use Tor for anonymity
          if ! curl -L -f -o schedule.json \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.5" \
            -H "Referer: https://daddylive.live/" \
            --socks5-hostname localhost:9050 \
            https://daddylive.mp/schedule/schedule-generated.php; then
            echo "::error::Failed to download schedule file"
            exit 1
          fi

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
          sudo systemctl start tor

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add schedule.json
          
          if git diff --quiet --cached; then
            echo "No changes to schedule.json"
          else
            git commit -m "Update schedule.json [skip ci]"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          fi

      - name: Archive schedule
        uses: actions/upload-artifact@v4
        with:
          name: schedule-backup
          path: schedule.json
          retention-days: 3

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Schedule Update Failed',
              body: 'The daily schedule update workflow failed. Please check the logs.'
            });