name: Update Schedule
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download schedule
        run: |
          if ! curl -L -f -o schedule.json https://daddylive.mp/schedule/schedule-generated.php; then
            echo "::error::Failed to download schedule file"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add schedule.json
          
          if git diff --quiet --cached; then
            echo "No changes to schedule.json"
          else
            git commit -m "Update schedule.json - $(date -u '+%Y-%m-%d %H:%M:%S') UTC [skip ci]"
            git push "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git"
          fi

      - name: Archive schedule
        uses: actions/upload-artifact@v4
        with:
          name: schedule-backup
          path: schedule.json
          retention-days: 3

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Schedule Update Failed',
              body: 'The daily schedule update workflow failed. Please check the logs.'
            });
